networks:
  loki:

services:
  loki:
    image: grafana/loki:3.0.0
    volumes:
      - ./data/loki/loki-local-config.yaml:/etc/loki/loki-local-config.yaml
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-local-config.yaml
    networks:
      - loki
  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./data/promtail/promtail-local-config.yaml:/etc/promtail/promtail-local-config.yaml
      - /var/log/nginx/access.log:/opt/access.log
    command: -config.file=/etc/promtail/promtail-local-config.yaml
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki
